language: bash

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y collectl shunit2
before_script:
  - git clone https://github.com/rodrigosiqueira/flextrace.git
  - cd flextrace
script:
  - ./run_tests.sh
notifications:
  email:
    recipients:
      - rodrigosiqueiramelo@gmail.com
    on_success: change
    on_failure: always

# safelist
branches:
  only:
  - master
  - stable
